### ISSUE TITLE
Add repository link to cargo.toml

### ISSUE THREAD

**Issue by edouardparis** [revault/revault_net#41]
add repository link to cargo.toml and push it to crates.io

**Comment by darosior** [comment]
Agreed for the repo link, i however don't think we should publish yet: i still have to come fix this library regularly as i implement new features downstream.

Before considering it final, we should:
- properly test the coordinator, which is implemented but rather hacky at the moment with important open issues
- implement and test the cosigning server, as well as its communication handling in revaultd (i'm on this)

Then we could release a revault_net v0.1 and implement Tor transport later on.
